title: Suleiman Sahawneh
logo: /assets/img/logo.png
description: Pricing analyst and incoming MS Business Analytics student at Cal State San Marcos.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
baseurl: ""
url: https://suleimansahawneh2.github.io
